作業状態の保存

diff --git a/add-pacman-repository b/add-pacman-repository
--- a/add-pacman-repository
+++ b/add-pacman-repository
@@ -1,307 +1,180 @@
 #/usr/bin/env bash
-if [ "$(whoami)" != "root" ]; then
-	echo "Need to be root or run with sudo. Exiting..."
-	exit 1
-fi
 
-set -u
-tmpdir="/tmp/add-pacman-repository-$(date +%Y%m%d%H%M%S)"
-reponame=""
-sigcheck=""
-sigtrust=""
-server=""
-selected=""
-yesorno=""
-keyid=""
+# add-pacman-repository - Add PPAs to pacman
+# Copyright (c) 2022-2023 Radio New Japan.
+# This software is licensed under 3-clause BSD license.
 
+set +u
 
-function main() {
-	while true;do
-		echo -e "Add a repository? [1=yes or 2=no]"
-		local yesorno
-		read -n1 yesorno
-		case ${yesorno} in
-			1) caution ;;
-			2) repo_abort ;;
-		esac
-	done
+_usage(){
+	echo "usage: add-pacman-repository [options]"
+	echo
+	echo "General Options:"
+	echo " -r | reponame <repo_name>                 Repository name"
+	echo " -f | --fingerprint <keyring fingerprint>  Keyring fingerprint"
+	echo " -k | --keyserver <key_server_url>         Key server URL"
+	echo " -p | --keypkg <keyring_package_url>       Keyring package URL"
+	echo " -m | --mirrorpkg <mirrorlist_package_url> Mirror list package URL"
+	echo " -s | --server <server_url>                Server URL"
+	echo " -i | --include <mirrorlist_path>          Path to mirror list"
+	echo " -l | --siglevel<r|o|a|n>                  Set SigLevel"
+	echo "      r     Required DatabaseOptional"
+	echo "      o     Optional TrustedOnly"
+	echo "      a     Optional TrustAll"
+	echo "      n     Never"
+	echo " -h | --help                               Show this help"
+	echo " -v | --version                            Show version info"
 }
 
-function caution() {
-	while true;do
-		yesorno=""
-		mkdir ${tmpdir}
-		echo ""
-		echo "!!!CAUTION!!!"
-		echo "While the script is running, you MUST NOT press any arrow keys or stop working in the middle."
-		repo_name
-	done
+_version(){
+	echo "add-pacman-repository ${APR_VERSION}"
+	echo "Adds Pacman PPAs to your environment"
+	echo
+	echo "Copyright (c) 2022-2023 Radio New Japan All Rights Reserved."
+	echo "This software is licensed under 3-clause BSD license."
 }
 
-function repo_name() {
-	while true;do
-		echo ""
-		echo "Enter repository name."
-		read reponame
-		if [[ ${reponame} == "" ]]; then
-			echo "Need to enter the repository name!"
-			repo_name
+_main(){
+	if [ "$(whoami)" != "root" ]; then
+		echo "ERROR: Need to run with root!"
+		exit 1
+	fi
+
+	mkdir -p /tmp/add-pacman-repository/pkg
+
+	if [[ ${KEYRING} == "fingerprint" ]]; then
+		if [[ ${KEYSERVER} == "" ]]; then
+			echo "ERROR: Specify the key server!"
+			exit 1
+		else
+			pacman-key --recv-key ${FINGERPRINT} --keyserver ${KEYSERVER}
+			pacman-key --lsign-key ${FINGERPRINT}
 		fi
+	fi
 
-		echo -e "\n[${reponame}]"|tee -a ${tmpdir}/preview.txt
-		siglevel_setting
-	done
+	if [[ ${REPO} == "mirrorlist" ]]; then
+		wget ${MIRRORPKG} -O /tmp/add-pacman-repository/pkg/${REPONAME}-mirrorlist.pkg.tar.zst
+		pacman -U --noconfirm /tmp/add-pacman-repository/pkg/${REPONAME}-keyring.pkg.tar.zst
+	fi
+
+	if [[ ${REPO} == "direct" ]]; then
+		echo "[${REPONAME}]"
+		echo "SigLevel = ${SIGLEVEL}"
+		echo "Server = ${SERVER}"
+	elif [[ ${REPO} == "mirrorlist" ]]; then
+		echo "[${REPONAME}]"
+		echo "SigLevel = ${SIGLEVEL}"
+		echo "Include = ${INCLUDE}"
+	fi
 }
 
-function siglevel_setting() {
-	while true;do
-		yesorno=""
-		echo ""
-		echo "Set SigLevel? [1=yes or 2=no]"
-		read -n1 yesorno
-		case ${yesorno} in
-			1) repo_siglevel ;; 
-			2) repo_key
-		esac
-	done
-}
+APR_VERSION="0.5"
 
-function repo_siglevel() {
-	while true;do
-		yesorno=""
-		echo ""
-		echo "Select the level of signature checking."
-		echo "1) Never    - All signature checking is suppressed."
-		echo "2) Optional - Signatures are checked if present."
-		echo "3) Required - Signatures are required."
-		read -n1 selected
-		case ${selected} in
-			1) echo "" && echo "SigLevel = Never"|tee -a ${tmpdir}/preview.txt;;
-			2) sigcheck=Optional ;;
-			3) sigcheck="Required DatabaseOptional" ;;
-		esac
+REPONAME=""
+KEYRING=""
+FINGERPRINT=""
+KEYSERVER=""
+KEYPKG=""
+MIRROR=""
+MIRRORPKG=""
+SERVER=""
+INCLUDE=""
+SIGLEVEL=""
+REPO=""
 
-		if [[ ${selected} == "1" ]]; then
-			repo_server
-		fi
+set +e
+_opt_short="r:f:k:p:m:s:i:l:hv"
+_opt_long="reponame:,fingerprint:,keyserver:,keypkg:,mirrorpkg:,server:,include:,siglevel:,help,version"
+OPT=$(getopt -o ${_opt_short} -l ${_opt_long} -- "${@}" 2> /dev/null)
+set -e
 
-		selected=""
-		echo ""
-		echo "Select the level of signature trusting."
-		echo "1) TrustedOnly - Signature must be fully trusted."
-		echo "2) TrustAll    - Signature isn't requred to be assigned a trust level."
-		read -n1 selected
-		case ${selected} in
-			1) sigtrust=TrustedOnly ;;
-			2) sigtrust=TrustAll    ;;
-		esac
-		echo ""
-		echo "SigLevel = ${sigcheck} ${sigtrust}"|tee -a ${tmpdir}/preview.txt
-		repo_key
-	done
-}
+eval set -- "${OPT}"
+echo "Arguments are \"${OPT}\""
+unset OPT _opt_short _opt_long
 
-function repo_key() {
-	while true;do
-		yesorno=""
-		selected=""
-		echo ""
-		echo "Where do you import keyrings from?"
-		echo "1) Keyring files    - Extensions such as .key or .gpg"
-		echo "2) Key ID           - From online servers"
-		echo "3) Keyring packages - Extensions such as .zst or .xz"
-		echo "4) Not import any keyrings"
-		read -n1 selected
-		case ${selected} in
-			1) key_file  ;;
-			2) key_server ;;
-			3) key_pkgs   ;;
-			4) key_noimport ;;
-		esac
-	done
-}
+while true; do
+	case "${1}" in
+		-h | --help)
+			_usage
+			exit 0
+			;;
+		-r | --reponame)
+			REPONAME="${2}"
+			shift 2
+			;;
+		-f | --fingerprint)
+			KEYRING="fingerprint"
+			FINGERPRINT="${2}"
+			shift 2
+			;;
+		-k | --keyserver)
+			KEYSERVER="${2}"
+			shift 2
+			;;
+		-p | --keypkg)
+			KEYRING="package"
+			KEYPKG="${2}"
+			shift 2
+			;;
+		-m)
+			if [[ ${2} == "" ]]; then
+				echo "ERROR: Specify the mirror list package!"
+				exit 1
+			else
+				MIRRORPKG="${2}"
+			fi
+			shift 2
+			;;
+		-s)
+			REPO="direct"
+			SERVER="${2}"
+			shift 2
+			;;
+		-i)
+			REPO="mirrorlist"
+			INCLUDE="${2}"
+			shift 2
+			;;
+		-l)
+			case ${2} in
+				r)
+					SIGLEVEL="Required DatabaseOptional"
+					;;
+				o)
+					SIGLEVEL="Optional TrustedOnly"
+					;;
+				a)
+					SIGLEVEL="Optional TrustAll"
+					;;
+				n)
+					SIGLEVEL="Never"
+					;;
+				*)
+					echo "ERROR: Invalid argument '${2}'!"
+					echo " r - Set SigLevel to 'Required DatabaseOptional'"
+					echo " o - Set SigLevel to 'Optional TrustedOnly'"
+					echo " a - Set SigLevel to 'Optional TrustAll'"
+					echo " n - Set SigLevel to 'Never'"
+					exit 1
+					;;
+			esac
+			shift 2
+			;;
+		-v)
+			_version
+			exit 0
+			;;
+		--)
+			shift 1
+			break
+			;;
+		*)
+			echo "ERROR: Invalid argument '${1}'!"
+			_usage
+			exit 1
+			;;
+	esac
+done
 
-function key_file() {
-	while true;do
-		yesorno=""
-		selected=""
-		echo ""
-		echo "Download a keyring file from the Internet."
-		echo "Enter the URL. (example: https://example.com/hogehoge.key)"
-		echo "(To return to the previous, press return key.)"
-		local keyurl
-		read keyurl
-		if [[ ${keyurl} = "" ]]; then
-			repo_key
-		fi
- 		mkdir ${tmpdir}/keyring
-		wget -O ${tmpdir}/keyring/archive.key ${keyurl}
-		pacman-key --add ${tmpdir}/keyring/archive.key
-		echo ""
-		echo "Sign to the key locally. Enter the Key-ID."
-		pacman-key --lsign-key ${keyid}
-		additional_keys
-	done
-}
+_main
 
-function key_server() {
-	while true;do
-		yesorno=""
-		echo ""
-		echo "Import keyring from the Internet. Enter the Key-ID."
-		echo "(To return to the previous, press return key.)"
-  read keyid
-		if [[ ${keyid} = "" ]]; then
-			repo_key
-		fi
-		echo "Specify the key-server. (example: pgp.mit.edu)"
-		local keyserver
-		read keyserver
-		if [[ ${keyserver} = "" ]]; then
-			echo "Need to enter the key server URL!"
-			key_server
-		fi
-		pacman-key --recv-key ${keyid} --keyserver ${keyserver}
-		pacman-key --lsign-key ${keyid}
-	additional_keys
-	done
-}
-
-function key_pkgs() {
-	while true;do
-		yesorno=""
-		echo ""
-		echo "Download a keyring package from the Internet. Enter the URL."
-		echo "(example: https://example.com/hoge/fuga-keyring-x.y.z-r-any.pkg.tar.zst)"
-		echo "(To return to the previous, press return key.)"
-		local pkgurl
-		read pkgurl
-		if [[ ${pkgurl} = "" ]]; then
-			repo_key
-		fi
- 		mkdir ${tmpdir}/keyring
-		wget -NP ${tmpdir}/keyring ${pkgurl}
-		yes|pacman -U ${tmpdir}/keyring/*.zst
-	additional_keys
-	done
-}
-
-function additional_keys() {
-	while true;do
-		echo "Import additional keys? [1=yes or 2=no]"
-		read -n1 yesorno
-		case ${yesorno} in
-			1) repo_key ;;
-			2) repo_server ;;
-		esac
-	done
-}
-
-function key_noimport() {
-	while true;do
-		echo ""
-		echo "!!!CAUTION!!!"
-		echo "Some repositories require additional keys."
-		echo "Are you sure you don't want to add them? [1=yes or 2=no]"
-		read -n1 yesorno
-		case ${yesorno} in
-			1) repo_server ;;
-			2) repo_key ;;
-		esac
-	done
-}
-
-function repo_server() {
-	while true;do
-		yesorno=""
-		selected=""
-		echo ""
-		echo "Use a mirror server list?"
-		echo "1) Yes   - Mirror lists are usually placed in /etc/pacman.d/"
-		echo "2) No    - Use a server listed directly in /etc/pacman.conf"
-		read -n1 yesorno
-		case ${yesorno} in
-			1) server_mirrorlist ;;
-			2) server_directly ;;
-		esac
-	done
-}
-
-function server_mirrorlist() {
-	while true;do
-		yesorno=""
-		echo ""
-		echo "Download a mirror list package from the Internet. Enter the URL."
-		echo "(example: https://example.com/hoge/fuga-mirrorlist-x.y.z-r-any.pkg.tar.zst)"
-		echo "(To return to the previous, press return key.)"
-		local pkgurl
-		read pkgurl
-		if [[ ${pkgurl} = "" ]]; then
-			repo_server
-		fi
-		yes|pacman -U "${pkgurl}"
-
-		echo "Enter the path to mirror list."
-		echo "(example: /etc/pacman.d/fuga-mirrorlist)"
-		local mirrorpath
-		read mirrorpath
-		if [[ ${mirrorpath} = "" ]]; then
-			echo "Need to enter the path to mirror list!"
-			server_mirrorlist
-		fi
-		echo "Include = ${mirrorpath}"|tee -a ${tmpdir}/preview.txt
-		sed -i 's/# Server/Server/g' ${mirrorpath}
-		repo_confirm
-	done
-}
-
-function server_directly() {
-	while true;do
-		yesorno=""
-		echo ""
-		echo "Enter the URL of repository."
-		echo "(example: https://example.com/hoge/x86_64)"
-		echo "(To return to the previous, press return key.)"
-		local serverurl
-		read serverurl
-		echo "Server = ${serverurl}"|tee -a ${tmpdir}/preview.txt
-		repo_confirm
-		done
-}
-
-function repo_confirm() {
-	while true;do
-		yesorno=""
-		echo ""
-		echo "Are you sure you want to add following content? [1=yes or 2=no]"
-		echo ""
-		cat ${tmpdir}/preview.txt
-		echo ""
-		echo ""
-		read -n1 yesorno
-		case ${yesorno} in
-			1) repo_end ;;
-			2) repo_abort ;;
-		esac
-	done
-}
-	
-function repo_end() {
-	echo "Writing to /etc/pacman.conf..."
-	cp /etc/pacman.conf /etc/pacman.conf.bak
-	cat ${tmpdir}/preview.txt|tee -a /etc/pacman.conf
-	pacman -Syyuu
-	rm -rf ${tmpdir}
-	echo "Done!"
-	echo ""
-	echo "If something goes wrong, run the following command to fix it:"
-	echo "sudo mv /etc/pacman.conf.bak /etc/pacman.conf"
-	exit 0
-}
-
-function repo_abort() {
-	echo ""
-	echo "Operation Aborted."
-	exit 0
-}
-	main
